name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install powershell with snapd
      run: sudo snap install powershell --classic
    - name: install GCC-11
      run: sudo apt install -y gcc-11
    - name: install G++-11
      run: sudo apt install -y g++-11
    - name: go to github repo
      run: cd ${{ github.workspace }}
    - name: pwsh
      run: pwsh -File build.ps1
