name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install powershell with snapd
      run: sudo snap install powershell --classic
    - name: go to github repo
      run: cd /github/workspace
    - name: pwsh
      run: pwsh -File build.ps1
