name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download powershell
      run: curl https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-lts_7.2.1-1.deb_amd64.deb
    - name: install powershell
      run: sudo dpkg -i powershell-lts_7.2.1-1.deb_amd64.deb
    - name: pwsh
      run: pwsh -File build.ps1
